name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "OutOfBoundsError" --password-stdin
        docker image build -t OutOfBoundsError/wish_list:latest .
        docker push OutOfBoundsError/wish_list:latest
